[package]
name = "run"
version = "1.0.1"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["consoleapi", "handleapi", "processenv", "winbase", "winnt"] }
regex = "1"

[build-dependencies]
winres = "0.1"
